### ISSUE TITLE
Логика в контроллерах

### ISSUE THREAD

**Issue by quolpr** [Ensemplix/Ensemplix-API#28]
Ребят, вам не кажется, что слишком много логики в контролерах? Это не rails best practise :). Вообще, лучше бы весь код из контроллеров вынести в модели и, что не мало важно, всё покрыть тестами. Так к вашему коду будет больше доверия и будет легче добавлять новые фичи так, чтобы другая логика не повредилась. Например, в том же https://github.com/Ensemplix/Ensemplix-API/blob/master/app/controllers/v2/shops_controller.rb в index слишком много join'ов. Это всё должно быть в модели. Кстати, для формирования ответа лучше использовать jbuilder - очень хороший инструмент.
Пожалуйста, не воспринимайте всё в штыки, я всего лишь хочу направить вас по верному вектору развития вашего проекта.

**Comment by ensirius** [comment]
Ваше замечание весьма уместно. Это была первая проба пера на данном языке и фреймворке. Заниматься улучшением структуры к сожалению времени нет. Но мы будем рады увидеть PR от вас с улучшениями :)
