### ISSUE TITLE
Противоречивые данные по игроку NiKe_

### ISSUE THREAD

**Issue by Jamim** [Ensemplix/Ensemplix-API#30]
API как бы говорит нам, что игрока нет, а история — есть.
http://api.ensemplix.ru/v2/player/info/NiKe_
http://api.ensemplix.ru/v2/shops/player/NiKe_

**Comment by ensirius** [comment]
В базе данных действительно нет такого игрока :( Не понятно

**Comment by ensirius** [comment]
Закрываю, но буду иметь ввиду если будет что-то подобное с другими никами.
