### ISSUE TITLE
Противоречивые данные по игрокам m4111 и LixPSx

### ISSUE THREAD

**Issue by Jamim** [Ensemplix/Ensemplix-API#31]
Аналогично проблеме #30.

http://api.ensemplix.ru/v2/player/info/m4111
http://api.ensemplix.ru/v2/shops/player/m4111

http://api.ensemplix.ru/v2/player/info/LixPSx
http://api.ensemplix.ru/v2/shops/player/LixPSx

**Comment by ensirius** [comment]
У нас было удаление неактивных игроков. Сенду 2 года. Я так понимаю что магазины пережили их владельцев. В ближайшие время мы планируем вайпнуть сенд и проблему считаю уже не актуальной. С точки зрения безопасности этих магазинов проблем нет.
