### ISSUE TITLE
AmberR2

### ISSUE THREAD

**Issue by Jamim** [Ensemplix/Ensemplix-API#33]
Приветствую, Владислав.

Рад, что Ensemplix не стоит на месте. Однако с вайпом Amber всплыла следующая проблема:
[Список серверов](http://api.ensemplix.ru/v2/server/game) содержит старое название для нового мира [AmberR2](http://api.ensemplix.ru/v2/shops?world=AmberR2), что затрудняет и делает менее очевидным автоматизацию добавления новых миров в сторонних приложениях.

Кроме того, новый мир имеет тот же id, что вносит ещё больше путаницы.

**Comment by ensirius** [comment]
Привет, исправил.
