### ISSUE TITLE
Переменная count /blocks/player/ всегда отображает 0

### ISSUE THREAD

**Issue by web93onv** [Ensemplix/Ensemplix-API#34]
Переменная count у нас значила к-во оставшихся блоков.
Если элементов в списке 120, то при сдвиге 0 (с учетом что на странице будет выдано 100 элементов), count будет равна 20, что будет означать что есть еще 20 элементов. При сдвиге в 100, к-во отображаемых элементов будет 20, а count будет равна 0.

Сейчас count в /blocks/player/ всегда имеет значение 0, из за чего нет возможности подсчитать к-во страниц.

http://api.ensemplix.ru/v2/blocks/player/?player=web93onv&offset=0
http://api.ensemplix.ru/v2/blocks/player/?player=web93onv&offset=100

**Comment by ensirius** [comment]
У нас в базе данных больше 200 миллион записей. Если я буду выводить для блоков их количество, то будет GG WP.
